apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-analyzer.fullname" . }}
  labels:
    {{- include "inference-analyzer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "inference-analyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-analyzer.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "inference-analyzer.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.openaiSecretName }}
          env:
            - name: "SERVER_PORT"
              value: "{{ .Values.ports.app }}"
          ports:
            - name: app
              containerPort: {{ .Values.ports.app }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: app
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            tcpSocket:
              port: app
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
