repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    labels:
      app: monitoring
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 76.3.0
    values:
      - prometheus/values.yaml

  - name: pg-admin-console
    labels:
      app: postgres
    namespace: data
    createNamespace: true
    chart: bitnami/postgresql
    version: 16.7.27
    values:
      - postgresql/values.yaml

  - name: redis
    labels:
      app: redis
    namespace: data
    createNamespace: true
    chart: bitnami/redis
    version: 19.5.0
    values:
      - redis/values.yaml

  - name: dynamodb
    namespace: data
    createNamespace: true
    chart: ./dynamodb/dynamodb

  - name: kafka
    namespace: data
    createNamespace: true
    chart: ./kafka/kafka

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    version: 6.6.2
    values:
      - loki/values.yaml

  - name: promtail
    namespace: monitoring
    chart: grafana/promtail
    version: 6.16.4
    values:
      - promtail/values.yaml
