apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingestor.fullname" . }}
  labels:
    {{- include "ingestor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "ingestor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ingestor.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "ingestor.fullname" . }}-config
          env:
            - name: "SERVER_PORT"
              value: "{{ .Values.ports.app }}"
            - name: "MANAGEMENT_PORT"
              value: "{{ .Values.ports.management }}"
          ports:
            - name: app
              containerPort: {{ .Values.ports.app }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.ports.management }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: management
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: management
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
