apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestor.fullname" . }}
  labels:
    {{- include "ingestor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  selector:
    {{- include "ingestor.selectorLabels" . | nindent 4 }}
  ports:
    - name: app
      port: {{ .Values.service.app.port }}
      targetPort: app
      protocol: TCP
