{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ingestor.fullname" . }}-management
  labels:
    {{- include "ingestor.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "ingestor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
