apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingestion-gateway.fullname" . }}-config
  labels:
    {{- include "ingestion-gateway.labels" . | nindent 4 }}
data:
  LOG_LEVEL_ROOT: {{ .Values.config.logLevel | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.config.actuatorEndpoints | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: {{ .Values.config.healthShowDetails| quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
