apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestion-gateway.fullname" . }}-management
  labels:
    {{- include "ingestion-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.management.type }}
  selector:
    {{- include "ingestion-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: management
      port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: TCP
