apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestion-gateway.fullname" . }}
  labels:
    {{- include "ingestion-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  selector:
    {{- include "ingestion-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: app
      port: {{ .Values.service.app.port }}
      targetPort: app
      protocol: TCP
