auth:
  username: admin_console_user
  password: admin_console_pass
  database: admin_console
primary:
  persistence:
    enabled: true
    size: 5Gi
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "latest"

