spring:
  application:
    name: inference-analyzer
  threads:
    virtual:
      enabled: true

server:
  port: ${INFERENCE_SERVER_PORT}

openai:
  base-url: ${OPENAI_BASE_URL}
  model: ${OPENAI_MODEL}
  temperature: ${OPENAI_TEMP}
  max-tokens: ${OPENAI_MAX_TOKENS}