spring:
  application:
    name: ingestor  # used by Micrometer tags, logs, etc.
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      retries: 3

server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_PORT:8081}
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true   # needed for p95/p99 latency charts
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
