name: ingestor-service-ci

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ development, 'feature/**', 'bugfix/**', 'hotfix/**' ]
    paths:
      - 'services/ingestor/**'
      - 'pom.xml'
      - '.github/workflows/ingestor-service-ci.yml'
      - '.github/workflows/_service-ci.yml'
  pull_request:
    paths:
      - 'services/ingestor/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_service-ci.yml
    with:
      service: ingestor
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
